<a href="https://colab.research.google.com/github/pennyLiu32/Tibame/blob/main/%E5%BD%88%E5%B9%95PART2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import urllib.request as req
import json
import pandas as pd
import os

def save_danmu_to_csv(sn, description=None):
    if description == None:
        dirname ="baha"
    else:
        dirname = f"baha/{description}"
    if not os.path.exists(dirname):
        os.makedirs(dirname)

    # url = "https://api.gamer.com.tw/anime/v1/danmu.php?videoSn={}&geo=TW%2CHK".format(sn)
    url = f"https://api.gamer.com.tw/anime/v1/danmu.php?videoSn={sn}&geo=TW%2CHK"
    f = req.urlopen(url)
    content = f.read()
    content = json.loads(content)

    danmus = content["data"]["danmu"]

    df = pd.DataFrame(danmus)
    df.to_csv(f"{dirname}/{sn}.csv",
        encoding="utf-8",
        index=False)
    return df

save_danmu_to_csv("26850", "鬼滅遊郭")

                   text    color  size  position   time        sn      userid
0              看完2刷2/15  #FFFFFF     1         0      0  25410397  amanda4a03
1                 好帥\n簽  #FFFFFF     1         2      0  25652598   s52241110
2                  油鍋篇！  #0036FA     2         2      0  29426133    Lucian01
3                     我  #FDE53D     1         0      0  33663511  kh69xvvspn
4     看封面就知道本片不適合老少咸宜觀看  #FF9625     2         2      6  45407686    d7261904
...                 ...      ...   ...       ...    ...       ...         ...
2996          善意什麼時候解開的  #FFFFFF     1         0  28053  28932406  safiya0820
2997     樓下白字說得對，沒有一個正常  #FFFFFF     1         0  28065  49967935    abcd7849
2998                 油鍋  #FFFFFF     1         0  28110  25430419   b30838695
2999               嗨\n嗨  #A7FE39     1         0  28119  27845675     coco447
3000        2025.7.27 *  #FFFFFF     1         0  28119  45877991     s935602

[3001 rows x 7 columns]

- 2: 成功
- 3: 轉址
- 4: 失敗
    - 404: Not Fount
    - 403: Forbidden
        - IP ban

- 送出: 網址+headers
- 回應: 回應+headers

- HTML:無數長方形(區塊)所構成

```python(html)
<>開始

</>結束

1. 名稱: 決定是甚麼
    a-> 超連結 img-> 圖片 video->影片

2. 屬性: 決定細節
    a href="網址"
    img/video scr="網址"
        <a href="網址">開始
        顯示內容
        </a>
3. 顯示內容
```

In [4]:
import urllib.request as req
# BeautifulSoup: 幫忙分析HTML
import bs4 as bs
# 這裡被擋是因為巴哈擋國外IP，所以在COLAB上執行會被拒絕
# url = "https://ani.gamer.com.tw/animeVideo.php?sn=26850"
url = "https://github.com/Elwing-Chou/tibame_20260714/raw/refs/heads/main/baha.html"
h = {
    "User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36"
}
r = req.Request(url, headers=h)
f = req.urlopen(r)
content = f.read()
# 型態轉換:
html = bs.BeautifulSoup(content)
# 專屬功能: find find_all(html名字, 篩選條件)
for link in html.find_all("a"):
    # 內容: .get_text()
    # 特殊屬性: ["href"]
    link_href = link["href"]
    if link_href.startswith("?sn"):
        print("下載彈幕", link_href)
        sn = link_href.split("=")[-1]
        save_danmu_to_csv(sn, description="鬼滅遊郭")

下載彈幕 ?sn=26850
下載彈幕 ?sn=27165
下載彈幕 ?sn=27166
下載彈幕 ?sn=27167
下載彈幕 ?sn=27339
下載彈幕 ?sn=27340
下載彈幕 ?sn=27592
下載彈幕 ?sn=27593
下載彈幕 ?sn=27867
下載彈幕 ?sn=27868
下載彈幕 ?sn=27869
下載彈幕 ?sn=30991
下載彈幕 ?sn=30992
下載彈幕 ?sn=30993
下載彈幕 ?sn=30994
下載彈幕 ?sn=30995
下載彈幕 ?sn=30996
下載彈幕 ?sn=30997
下載彈幕 ?sn=30998
下載彈幕 ?sn=30999
下載彈幕 ?sn=31000
下載彈幕 ?sn=31001

In [5]:
import os
import glob
# glob可以幫忙找到符合需要的東西
import pandas
total = []

for fp in glob.glob("baha/*/*.csv"):
    df = pd.read_csv(fp, encoding="utf-8")
    sn = os.path.basename(fp).replace(".csv", "")
    # dataframe增加新行
    df["sn"] = sn
    total.append(df)

total_df = pd.concat(total)
# 如果你想reset列標籤 total_df = total_df.reset_index()
total_df

                   text    color  size  position   time     sn        userid
0                 沒人!!!  #FFFFFF     1         0      0  31000  comyouhelpme
1                     簽  #A7FE39     1         0      0  31000      k9219059
2     2022.8.22  簽 耶～～😋  #FF02D3     1         0      1  31000   Amy20080403
3                hhhhhi  #FFFFFF     1         0     10  31000  ltes11150414
4                  蠟筆小新  #FFFFFF     1         0     29  31000     skos12345
...                 ...      ...   ...       ...    ...    ...           ...
2996            第六集1/9播  #BEBEBE     2         0  14200  27339  BHSN00003u38
2997            (´･ω･`)  #FFFFFF     1         0  14200  27339    aaaa970614
2998               笑死欸幹  #FFFFFF     1         0  14200  27339   Tuhanss0606
2999       帶著智慧型手機闖蕩異世界  #FFFFFF     1         0  14200  27339   pq107352876
3000        2025.7.28 *  #FFFFFF     1         0  14200  27339       s935602

[36003 rows x 7 columns]

- pandas兩大操作
    - 過濾: 過濾你想要的row
    - 轉換: 轉換你需要轉換的 col

In [6]:
# 過濾: 準備跟你資料筆數一樣多的True/False
fil = [True, False, True]
total_df.head(3)[fil]

                text    color  size  position  time     sn        userid
0              沒人!!!  #FFFFFF     1         0     0  31000  comyouhelpme
2  2022.8.22  簽 耶～～😋  #FF02D3     1         0     1  31000   Amy20080403

In [9]:
# total_df["userid"] == "k9219059"
# value_counts() unique()
names = total_df["userid"].unique()

dirname = "analyse/鬼滅"
if not os.path.exists(dirname):
    os.makedirs(dirname)
for n in names:
    fil = total_df["userid"] == n
    total_df[fil].to_csv(f"{dirname}/{n}.csv",
                encoding="utf-8",
                index=False)